apiVersion: v1
kind: Service
metadata:
  name: mongo-mongos
  labels:
    app: mongo-mongos
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
      nodePort: 30007
  selector:
    app: mongo-mongos
