apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1-headless
  labels:
    app: mongo-shard1
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None
  selector:
    app: mongo-shard1
