apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: twutter-app

resources:
- deployment.yaml
- service.yaml
- secret.yaml
- registry-secret.yaml

labels:
- pairs:
    app: twutter-app 