apiVersion: v1
kind: Service
metadata:
  name: twutter-service
  labels:
    app: twutter-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30006
    protocol: TCP
    name: http
  selector:
    app: twutter-app 