stages:
  - build
  - deploy

build_and_push_docker_image:
  # Use a standard Docker image for the job
  image: docker:latest
  
  # Define the stage for the job
  stage: build

  # Use the Docker-in-Docker service to allow building images
  services:
    - docker:dind

  # Define necessary environment variables for Docker-in-Docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  # Log in to the GitLab Container Registry before running the script
  # This uses predefined CI/CD variables for secure authentication
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  # The main script for building and pushing the image
  script:
    # Build the Docker image.
    # --build-arg passes the secure CI/CD variable to the Dockerfile.
    # The last argument './twutter' tells Docker to use the 'twutter'
    # subdirectory as the build context.
    - |
      docker build \
        --pull \
        --build-arg MONGO_URI_ARG="$MONGO_URI" \
        -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" \
        -t "$CI_REGISTRY_IMAGE:latest" \
        ./twutter

    # Push the newly built image to the GitLab Container Registry
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"

  # This job will only run when changes are pushed to the 'main' branch.
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy_to_host:
  image: alpine:latest
  stage: deploy
  variables:
    DEPLOYMENT_HOST_HOSTNAME: $DEPLOYMENT_HOST_HOSTNAME
    DEPLOYMENT_HOST_IP: $DEPLOYMENT_HOST_IP
    DEPLOYMENT_HOST_SSH_KEY: $DEPLOYMENT_HOST_SSH_KEY
  script:
    - apk add --no-cache openssh
    - chmod 600 "$DEPLOYMENT_HOST_SSH_KEY"
    - |
      ssh -o StrictHostKeyChecking=no -i "$DEPLOYMENT_HOST_SSH_KEY" "$DEPLOYMENT_HOST_HOSTNAME"@${DEPLOYMENT_HOST_IP} '
        # Check if the cluster is configured
        if ! kubectl cluster-info >/dev/null 2>&1; then
          echo "Cannot connect to Kubernetes cluster. Skipping deployment."
          exit 0
        fi
        
        # Check if twutter deployment exists
        if kubectl get deployment twutter-app >/dev/null 2>&1; then
          echo "Twutter deployment found. Restarting..."
          kubectl rollout restart deployment/twutter-app
          kubectl rollout status deployment/twutter-app --timeout=300s
          echo "Twutter deployment restarted successfully"
        else
          echo "Twutter deployment not found. Skipping deployment."
          exit 0
        fi
      '
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - build_and_push_docker_image