apiVersion: v1
kind: Service
metadata:
  name: mongo-csrs-headless
  labels:
    app: mongo-csrs
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None
  selector:
    app: mongo-csrs
