apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-mongos
  template:
    metadata:
      labels:
        app: mongo-mongos
    spec:
      containers:
        - name: mongos
          image: mongo:8.0.9
          command:
            - "mongos"
            - "--configdb"
            - "rsConfig/mongo-csrs-0.mongo-csrs-headless.default.svc.cluster.local:27017,mongo-csrs-1.mongo-csrs-headless.default.svc.cluster.local:27017,mongo-csrs-2.mongo-csrs-headless.default.svc.cluster.local:27017"
            - "--port"
            - "27017"
            - "--bind_ip_all"
            - "--keyFile"
            - "/etc/mongo-secrets/mongo-keyfile"
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-keyfile-volume
              mountPath: /etc/mongo-secrets
              readOnly: true
      volumes:
        - name: mongo-keyfile-volume
          secret:
            secretName: mongo-keyfile
            defaultMode: 0400
