apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-volume-xfs
provisioner: cinder.csi.openstack.org
parameters:
  type: __DEFAULT__
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer