apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-add-shards
  labels:
    app: {{ .Release.Name }}-add-shards
    release: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-add-shards
  labels:
    app: {{ .Release.Name }}-add-shards
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-add-shards
  labels:
    app: {{ .Release.Name }}-add-shards
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-add-shards
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-add-shards
  namespace: {{ .Release.Namespace }} 