apiVersion: v1
kind: Secret
metadata:
  name: mongo-cluster-admin-password
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  username: bW9uZ29hZG1pbg==  # base64 of 'mongoadmin'
  password: c2VjdXJlcGFzc3dvcmQ=  # base64 of 'securepassword'
